### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by mark-hammond** [kathlandgren/SWAMPE#4]

**Comment by mark-hammond** [comment]
1) Could you provide the output data for the 0.1, 1, and 10 day tau_rad simulations in https://swampe.readthedocs.io/en/latest/notebooks/QuickStart.html, as well as the exact input parameters (including runtime and timestep) for an exact comparison?

**Comment by mark-hammond** [comment]
2. I suggest citing Dedalus (https://dedalus-project.org/citations/) in "Similar Tools" as an example of a Python code that can handle spherical shallow-water equations. Also the spectral GFDL FMS (https://www.gfdl.noaa.gov/idealized-spectral-models-quickstart/) is an example of another GCM that can also run in shallow-water mode, like mitGCM.

**Comment by dfm** [comment]
Adding a reference to https://github.com/openjournals/joss-reviews/issues/4872 for tracking purposes.

**Comment by kathlandgren** [comment]
Thank you for your comments! Apologies for the delay in addressing them. 

1. The output data and the scripts used to generate it have been added to [this folder](https://github.com/kathlandgren/SWAMPE/tree/main/docs/source/notebooks/hot_Jupiter_reference_example) and linked from the relevant section of QuickStart.
2.  References to these tools have been added to the paper.
